spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/core
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

app:
  aws:
    profile: cac-sso-workloads-dev
    region: ap-northeast-2
    secret-name: dev/oauth-secret
  cookie-domain: localhost
  client-base-url: http://localhost:5173
  server-base-url: http://localhost:8000
  jwt-secret-key: local-dev-secret-key-must-be-at-least-32-bytes-long
  access-token-expiration-seconds: 900
  refresh-token-expiration-seconds: 1209600

decorator:
  datasource:
    p6spy:
      enable-logging: true
