version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: app_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: core
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d core"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
